# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
      # As of kernel 6.2, the vfio_virqfd functionality has been folded into the base vfio module
      kernelModules = [ "zfs" "vfio_pci" "vfio" "vfio_iommu_type1" "vfio_virqfd" ];
      supportedFilesystems = [ "zfs" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    kernelParams = [
      "intel_iommu=on"
      "iommu=pt"
      "vfio-pci.ids=8086:1901,10de:1f08,10de:10f9,10de:1ada,10de:1adb"
    ];
  };

  fileSystems."/" =
    { device = "rpool/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/nixos/home";
      fsType = "zfs";
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/E96E-9350";
      fsType = "vfat";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/68d4adf2-653d-43ce-b031-196e7e909141";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking = {
    hostId = "8ba03bf4";
    hostName = "planet3";
    useDHCP = lib.mkDefault false;
  };
  systemd.network = {
    enable = true;
    netdevs = {
      "10-virbr9" = {
        netdevConfig = {
          Kind = "bridge";
          Name = "virbr9";
        };
      };
    }; 
    networks = {
      "20-enp5s0" = {
        matchConfig.Name = "enp5s0";
        networkConfig.Bridge = "virbr9";
        linkConfig.RequiredForOnline = "enslaved";
      };
      "30-virbr9" = {
        matchConfig.Name = "virbr9";
        networkConfig.DHCP = "yes";
      };
    };
  };
  virtualisation.libvirtd.allowedBridges = [ "virbr0" "virbr9" ];
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
