name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  secret: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup BackendC
        run: |
          cd kerbal-dashboard
          npm i

      - name: Build DashBoard
        run: |
          docker build -t backend:01 . 

      - name: Test DashBoard
        run: |
          cd kerbal-dashboard
          npm run testall

      - name: Test Backend
        run: |
          docker run backend:01 /check.sh